name: Publish to PyPI

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Check package version
      run: |
        package_version=$(poetry version | cut -d' ' -f2)
        tag_name=${{ github.event.release.tag_name }}
        if [ "${tag_name#v}" != "$package_version" ]; then
          echo "ERROR: Package version does not match release tag"
          echo "Package version: $package_version, tag name: $tag_name"
          exit 1
        fi

    - name: Build package
      run: poetry build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
