name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        make install

    - name: Run tests
      run: make test

    - name: Check code formatting and lint
      run: make format-check

    - name: Test building the package
      run: make build

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
